pipeline {
    agent any
    stages {
        stage('Clone') {
            steps {
                git url: 'https://github.com/HarshaDoda/devops-project.git',branch: 'main'
            }
        }
        stage('Build Backend') {
            steps {
                sh 'docker build -t devops-backend ./backend'
            }
        }
        stage('Build Frontend') {
            steps {
                sh 'docker build -t devops-frontend ./frontend'
            }
        }
        stage('SonarQube Analysis') {
            steps {
                echo 'Skipping SonarQube analysis (SonarQube is not running)'
            }
        }
    }
}
