pipeline {
    agent any
    stages {
        stage('Clone') {
            steps {
                git 'https://github.com/your/repo.git'
            }
        }
        stage('Build Backend') {
            steps {
                sh 'docker build -t devops-backend ./backend'
            }
        }
        stage('Build Frontend') {
            steps {
                sh 'docker build -t devops-frontend ./frontend'
            }
        }
        stage('SonarQube Analysis') {
            steps {
                withSonarQubeEnv('MySonar') {
                    sh 'sonar-scanner'
                }
            }
        }
    }
}
